nginxproxy:
  image: jwilder/nginx-proxy
  restart: always
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

site:
  build: .
  restart: always
  expose:
    - "80"
#    - "443"
  environment:
    VIRTUAL_HOST: robboros.com,www.robboros.com,boros.remlabm.com
    VIRTUAL_PORT: 80
